grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2
model_selection:
  module_0:
    class: LinearRegression
    module: sklearn.linear_model
    params:
      fit_intercept: True
    search_param_grid:
      fit_intercept:
      - True
      - False
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 2
      max_features: 7
      n_estimators: 100
      max_depth: 5
    search_param_grid:
      min_samples_leaf:
      - 2
      max_features:
      - 7
      n_estimators:
      - 100
      max_depth:
      - 5
  module_2:
    class: XGBRegressor
    module: xgboost
    params: 
      n_estimators: 500
      max_depth: 3
      eta: 0.01
      colsample_bytree: 1.0
    search_param_grid:
      n_estimators: 
        - 500

      


